spring:
  application:
    name: book-social-network

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksocialnetwork

  servlet:
    multipart:
      max-file-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: arpitrathorexyz@mail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  default-produces-media-type: application/json

server:
  port: 8088

  servlet:
    context-path: /api/v1/

application:
  activationCodeLength: 6

  mailing:
    activation-url: http://localhost:4200/activate-account

  file:
    upload:
      photos-output-path: ./uploads

  security:
    jwt:
      secret-key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
      expiration: 8640000
